# Generated by Django 5.0.1 on 2024-01-11 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NavBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=10)),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'navbars',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.CreateModel(
            name='NavBarToggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('link', models.CharField(max_length=10)),
                ('order', models.IntegerField()),
                ('navbar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.navbar')),
            ],
            options={
                'verbose_name_plural': 'navbartoggles',
            },
        ),
    ]
