# Generated by Django 5.0.1 on 2024-01-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_navbar_alter_category_options_navbartoggle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('title', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('order', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'testimonials',
            },
        ),
        migrations.AlterField(
            model_name='navbar',
            name='name',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='navbartoggle',
            name='name',
            field=models.CharField(max_length=15),
        ),
    ]
