# Generated by Django 5.0.1 on 2024-01-12 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_category_options'),
        ('home', '0003_testimonial_alter_navbar_name_and_more'),
    ]

    operations = [
    ]
