# Generated by Django 5.0.1 on 2024-01-17 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_merge_20240111_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='img/'),
        ),
    ]
